-- V73 PostgreSQL transition.
-- This legacy SQLite migration is intentionally a no-op for the new empty PostgreSQL database.
-- The complete PostgreSQL schema is created by 20260927003000_postgres_baseline.
